version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s : %(message)s"
  json:
    class: pythonjsonlogger.json.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s %(client_id)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

loggers:
  app:
    handlers: [console]
    level: INFO
    propagate: False

  httpx:
    level: WARNING
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
