version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s : %(message)s"
  json:
    class: pythonjsonlogger.json.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s %(client_id)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

loggers:
  httpx:
    level: INFO
    handlers: [console]
    propagate: no

  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: False

  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: False

  langchain_mcp_adapters:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console]
