apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weather-mcp.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "weather-mcp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: {{ include "weather-mcp.chart" . }}
data:
  logging.yaml: |
    {{ .Files.Get "config/logging.yaml" | indent 4 }}
  logging.{{ .Values.env.ENV }}.yaml: |
    {{ .Files.Get (printf "config/logging.%s.yaml" .Values.env.ENV) | indent 4 }}
