apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weather-mcp.fullname" . }}-config
  labels:
    {{- include "weather-mcp.labels" . | nindent 4 }}
data:
  logging.yaml: |
    {{ .Files.Get "config/logging.yaml" | indent 4 }}
  logging.{{ .Values.env.ENV }}.yaml: |
    {{ .Files.Get (printf "config/logging.%s.yaml" .Values.env.ENV) | indent 4 }}
