{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "weather-mcp.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "weather-mcp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: {{ include "weather-mcp.chart" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "weather-mcp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
