{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-mcp.fullname" . }}
  labels:
    {{- include "weather-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
