{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "weather-mcp.fullname" . }}-servicemonitor
  labels:
    release: prometheus
    {{- include "weather-mcp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "weather-mcp.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.monitoring.serviceMonitor.port }}
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
