FROM python:3.10-alpine3.22

# Upgrade pip
RUN pip install --upgrade pip

# Install poetry
RUN pip install poetry

# Set working directory
WORKDIR /app

ENV PYTHONPATH=/src

# Copy only dependency files first (for caching)
COPY pyproject.toml poetry.lock ./

# Install dependencies
RUN poetry install --no-root --without dev

# Copy the rest of the project
COPY config /app/config
COPY src/config /app/src/config
COPY src/weather_mcp /app/src/weather_mcp

# Default command
CMD ["poetry", "run", "python3", "app/src/weather_mcp/main.py"]
